language: ruby

rvm:
  - 2.2.5

sudo: required
services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1204
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-debian-7
  - INSTANCE=default-debian-8

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

install:
  # setup ci for test formula
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install

script:
  # Run unit tests
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen verify ${INSTANCE}
